### ISSUE TITLE
bug: Ctrl+e glitches and stops scrolling down after first press if starting at top of file

### ISSUE THREAD

**Issue by roryfahy** [tobealive/german-scroll.code#4]

**Comment by roryfahy** [comment]
on Mac Ventura

**Comment by roryfahy** [comment]
Also just wanted to say thank you for this extension, it rocks!

**Comment by tobealive** [comment]
Hey @roryfahy,

thanks for reaching out. Sorry about that issue, but glad to hear you like it so far!

I'll get a few things done by the end of the week and take a closer look.

But I haven't been able to reproduce the problem yet, so maybe you can help me get there until then. Are you using change values / are there other characteristics like folds, or does the problem occur with every document?

**Comment by tobealive** [comment]
let me know how it behaves with the latest release :+1:

**Comment by tobealive** [comment]
I finally could reproduce the bug when setting up vscode on another box and handn't yet the `Editor: Smooth Scrolling` setting enabled. Especially for changes since 0.2.0 version the smooth scrolling setting had become a requirement. I extend the readme to include this.

**Comment by roryfahy** [comment]
Thank you I will test it out. 🙏
